### ISSUE TITLE
ValueError: Tagger is not opened

### ISSUE THREAD

**Issue by jigishaSA** [Rutvik-Trivedi/Gujarati-NLP-Toolkit#2] opened 2021-06-01 08:08 UTC
તારુ નામ શુ છે?
['તારુ', 'નામ', 'શુ', 'છે']
[['WORD_તારુ', 'SUF_ુ', 'PRE_ત', 'SUF_રુ', 'PRE_તા', 'SUF_ારુ', 'PRE_તાર', 'SUF_મ', 'PRE_ન', 'SUF_ામ', 'PRE_ના', 'NEXT_WORD_નામ', 'SUF_ુ', 'PRE_શ', 'NEXT_NEXT_WORD_શુ'], ['WORD_નામ', 'SUF_મ', 'PRE_ન', 'SUF_ામ', 'PRE_ના', 'SUF_ુ', 'PRE_ત', 'SUF_રુ', 'PRE_તા', 'SUF_ારુ', 'PRE_તાર', 'PREV_WORD_તારુ', 'SUF_ુ', 'PRE_શ', 'NEXT_WORD_શુ', 'SUF_ે', 'PRE_છ', 'NEXT_NEXT_WORD_છે'], ['WORD_શુ', 'SUF_ુ', 'PRE_શ', 'SUF_મ', 'PRE_ન', 'SUF_ામ', 'PRE_ના', 'PREV_WORD_નામ', 'SUF_ુ', 'PRE_ત', 'SUF_રુ', 'PRE_તા', 'SUF_ારુ', 'PRE_તાર', 'PREV_PREV_WORD_તારુ', 'SUF_ે', 'PRE_છ', 'NEXT_WORD_છે'], ['WORD_છે', 'SUF_ે', 'PRE_છ', 'SUF_ુ', 'PRE_શ', 'PREV_WORD_શુ', 'SUF_મ', 'PRE_ન', 'SUF_ામ', 'PRE_ના', 'PREV_PREV_WORD_નામ']]
Traceback (most recent call last):
  File "pos_guj.py", line 4, in <module>
    print(tagger.pos_tag(sen))
  File "/home/jigisha/Desktop/Gujarati-NLP-Toolkit-master/posTagger.py", line 213, in pos_tag
    tags = self.tag(sent)
  File "/home/jigisha/.local/lib/python3.8/site-packages/nltk/tag/crf.py", line 210, in tag
    return self.tag_sents([tokens])[0]
  File "/home/jigisha/.local/lib/python3.8/site-packages/nltk/tag/crf.py", line 168, in tag_sents
    labels = self._tagger.tag(features)
  File "pycrfsuite\_pycrfsuite.pyx", line 637, in pycrfsuite._pycrfsuite.Tagger.tag
  File "pycrfsuite\_pycrfsuite.pyx", line 695, in pycrfsuite._pycrfsuite.Tagger.set
ValueError: Tagger is not opened.

As feature list is generated (as printed above) in crf.py file. so kindly help me solve this issue

**Comment by jigishaSA** [comment] 2021-06-01 08:21
self._tagger.tag takes feature list as dict but here it is as list. up to this i have solved. further i want help.

**Comment by Rutvik-Trivedi** [comment] 2021-06-01 09:17
Hi @jigishaSA,
Thanks for reaching out. Due to some other higher priority works coming up constantly since quite some time, I have not been able to actively maintain this project. But I am now planning to maintain this repository as people are noticing this project and there are a few stargazers and even users who are finding this project interesting.
  
And as far as your query is concerned, I actually had planned to migrate the dependencies used from ```sklearn-crfsuite``` to ```nltk```'s CRFTagger. Due to that, the usage structure of the posTagger changed. And unfortunately, there was a small bug which went unnoticed. I have fixed the bug now and pushed the code to the ```dev``` branch for now. After proper testing and adding some more features I planned, I shall merge it to the main branch.

To solve your problem, you can clone the development branch by running
```bash
git clone --single-branch --branch dev https://github.com/Rutvik-Trivedi/Gujarati-NLP-Toolkit.git
```
and repeat the steps as belows:
```python
from posTagger import posTagger
tagger = posTagger(corpus='prose')    # As 'તારુ નામ શુ છે?' is a normal sentence and not considered a poetry
tagger.eval()
tagger.pos_tag('તારુ નામ શુ છે?')
```

Alternatively, you can make the changes in your local repository by referring to the changes in the development branch. I have changed the following to files:
1. posTagger.py
2. tokenizer.py
and repeat the above python code. It should work fine now.

Having said this, please inform me here in case the problem still persists and I shall be happy to help. Thank you for pointing out this bug and helping this project improve. If the problem is solved after this solution, please do close this issue without fail.

**Comment by jigishaSA** [comment] 2021-06-01 10:14
raceback (most recent call last):
  File "pos_guj.py", line 2, in <module>
    tagger = pt.posTagger(corpus='prose') 
TypeError: __init__() got an unexpected keyword argument 'corpus'

and as in implementation detail 

import posTagger as pt
tagger = pt.posTagger('model_name')   # Give any name for your model
train_X, train_y = tagger.data_from_corpus('path/to/corpus/')

data_from_corpus not an tagger attribute

**Comment by Rutvik-Trivedi** [comment] 2021-06-01 12:50
> raceback (most recent call last):
> File "pos_guj.py", line 2, in
> tagger = pt.posTagger(corpus='prose')
> TypeError: init() got an unexpected keyword argument 'corpus'

@jigishaSA, this error is because you are still using the repository of master branch. If you would take a look at the codebase of the ```master``` branch in the ```posTagger.py``` file, you will find only 2 arguments in the ```__init___``` function, ```model``` and ```verbose```. Hence it is giving this error that ```corpus``` argument is not present. If you will see the ```posTagger.py``` file in the ```dev``` branch, you will see the ```corpus``` argument present. So, I would recommend you to delete the repository folder and clone the development branch ```dev``` for this by running
```bash
git clone --single-branch --branch dev https://github.com/Rutvik-Trivedi/Gujarati-NLP-Toolkit.git
```

> 
> import posTagger as pt
> tagger = pt.posTagger('model_name') # Give any name for your model
> train_X, train_y = tagger.data_from_corpus('path/to/corpus/')
> 
> data_from_corpus not an tagger attribute


Here, think you are trying to write the code based on the README file in the repository. The README file is currently outdated as it is showing the code usage of the Sklearn based model. I have already added the warning as a ```NOTE``` in the README file. In case you want to train the POS Tagger, use the following code
```python
from posTagger import posTagger
tagger = posTagger(verbose=True, corpus='prose')
train_data = tagger.structure_data('path/to/your/data/file.csv')
tagger.train(train_data, tagger._model_file)
```
This will train the model and create a model file named ```guj.crf.pkl``` in your working directory.
  
To make an inference, after training, do the following
```python
from posTagger import posTagger
tagger = posTagger(corpus='prose')    # As 'તારુ નામ શુ છે?' is a normal sentence and not considered a poetry
tagger.eval()    # This will set the tagger into evaluation/inference mode
tagger.pos_tag('તારુ નામ શુ છે?')
```

In case you are a beginner and might have difficulty understanding and reproducing all these steps, I would recommend you to wait for some time. I shall update the README and check and merge the development branch to the master and then you shall be able to normally clone and use the code. Please do try out these steps and let me know in case you have any problems or encounter any bugs. Thanks for using the project and helping it improve.

**Comment by Rutvik-Trivedi** [comment] 2021-06-02 16:18
Hi @jigishaSA , thank you for your patience. I have merged the development branch to the master branch. You can refer to the documentation now and try out the code. Please do not forget to update your local repository with the newest code. Thanks.

**Comment by jigishaSA** [comment] 2021-06-07 04:41
Thank you for response now its working

**Comment by Rutvik-Trivedi** [comment] 2021-06-07 05:08
Great! Closing the issue now.

**Closed as completed by Rutvik-Trivedi** 2021-06-07 05:08 UTC
Labels: question, acknowledged

**Comment by jigishaSA** [comment] 2021-06-07 06:39
can't train my model. show following error. plz help to sovle

Traceback (most recent call last):
  File "pos_guj.py", line 5, in <module>
    train_data = tagger.structure_data('/home/jigisha/Downloads/HIN-GUJ_Sample/Sample_Gujarati.txt')
  File "/home/jigisha/Desktop/new_pos/Gujarati-NLP-Toolkit-dev/posTagger.py", line 197, in structure_data
    data = self.collect_train_data(file)
  File "/home/jigisha/Desktop/new_pos/Gujarati-NLP-Toolkit-dev/posTagger.py", line 176, in collect_train_data
    data = pd.read_csv(file)
  File "/home/jigisha/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 611, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/jigisha/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 469, in _read
    return parser.read(nrows)
  File "/home/jigisha/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1059, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/jigisha/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 2064, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1951, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 8, saw 2
